remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gustavo Rodríguez Alonso
logo: /images/rodag.jpg
description: Gustavo Rodríguez Alonso
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
